# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller recipe for the native Windows desktop application."""

from pathlib import Path


ROOT = Path(SPECPATH).resolve()


def data_tree(source_name):
    """Collect source assets without test-generated bytecode caches."""
    source = ROOT / source_name
    rows = []
    for path in source.rglob('*'):
        if path.is_file() and '__pycache__' not in path.parts:
            relative_parent = path.relative_to(source).parent
            destination = Path(source_name) / relative_parent
            rows.append((str(path), str(destination)))
    return rows


datas = data_tree('data') + data_tree('internal_tools') + [
    (str(ROOT / 'VERSION.txt'), '.'),
]

a = Analysis(
    [str(ROOT / 'native_app.py')],
    pathex=[str(ROOT)],
    binaries=[],
    datas=datas,
    # These are imported by helper scripts loaded from internal_tools at run time,
    # so static analysis of native_app.py cannot discover them.
    hiddenimports=['PIL.ImageDraw', 'PIL.ImageFont'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='NASCARModdingApp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='NASCARModdingApp',
)
